### ISSUE TITLE
Wrong / broken e-mail adress "cohesity-api-sdks@cohesity.com"

### ISSUE THREAD

**Issue by kortstie** [cohesity/cohesity-ansible-role#14]
The Mail adress which is public posted under your feedback section  seems to be wrong.
I get a mail delevery error from googlemail after I tried do send you an mail...

BR

Frank

**Comment by sagnihotri-cohesity** [comment]
Hi @kortstie , just verified. This is indeed the correct email address and seems to be working fine: cohesity-api-sdks@cohesity.com

**Comment by kortstie** [comment]
Hi Shreyas, just send a testmail to the 'cohesity-api-sdks@cohesity.com' and got directly this mail delivery error...
-----Ursprüngliche Nachricht-----
Von: Mail Delivery Subsystem <mailer-daemon@googlemail.com> 
Gesendet: Dienstag, 22. Januar 2019 07:27
An: prvs=918ae6d4b=frank.kortstiege@westlotto.com
Betreff: Delivery Status Notification (Failure)

Hello frank.kortstiege@westlotto.com,

We're writing to let you know that the group you tried to contact (cohesity-api-sdks) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/cohesity.com/bin/topic.py?topic=25838.

Thanks,

cohesity.com admins

**Comment by sagnihotri-cohesity** [comment]
Thanks for pasting the error snippet, that helped. I have updated the posting permissions for external senders. Can you please try one more time?

**Comment by kortstie** [comment]
Just sent another Testmail and got no delivery error yet, please check the api-sdk mailbox...

**Comment by sagnihotri-cohesity** [comment]
Got your email. Marking this as resolved.
