### ISSUE TITLE
[feature request] - cohesity_agent: agent installation on isolated hosts / DMZ

### ISSUE THREAD

**Issue by kortstie** [cohesity/cohesity-ansible-role#15]
We have many webservers which can't reach the cohesity API directly, therefore I can't install the Agent with the ansible role.
In the past I wrote my own playbook which copied the agent installer to these systems and installs / upgrades it then locally on the webserver...
A function to manage such isolated hosts integrated in your role would be really helpful!

**Comment by goodrum** [comment]
We can definitely include an option like this in a future release.  Additionally, we could offer a _create-if-not-exist_ option to the agent installer so that you can `copy` from the local host in your playbook but leverage the rest of the agent management (bypass download)

**Comment by anvesh-cohesity** [comment]
**download_uri**  parameter addresses this requirement. The installer can be hosted on any server, the module makes a simple GET call to get the installer onto the target machine. 
The enhancement is in the master and Cohesity Ansible role on Ansible Galaxy. Check the documentation for more details https://cohesity.github.io/cohesity-ansible-role/#/modules/cohesity_agent
