### ISSUE TITLE
[feature request] - cohesity_job: limit the vm's added managed by a job

### ISSUE THREAD

**Issue by kortstie** [cohesity/cohesity-ansible-role#19]
I suggest to add a parameter "vm_names" to the cohesity_job module to limit the Virtual Machines managed by a protection job.
Example:
  - cohesity_job:
      cluster: "{{ var_cohesity_server }}"
      username: "{{ var_cohesity_admin }}"
      password: "{{ var_cohesity_password }}"
      ....
      protection_sources:
       - another.v.center
      vm_names:
        - myvm1.my.domain
        - myvm2.my.domain
        ....

**Comment by anvesh-cohesity** [comment]
Supported with **include** parameter. The enhancement is in the master and Cohesity role on Ansible Galaxy
