### ISSUE TITLE
[feature-request] - cohesity_restore_vm: module should select the protection job on its own

### ISSUE THREAD

**Issue by kortstie** [cohesity/cohesity-ansible-role#20]
When I call the cohesity_resotre_vm module, and leave the job_name parameter, the module exits with the following errror:
...
/tmp/ansible-tmp-1549545897.5-200667828612790/AnsiballZ_cohesity_restore_vm.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod
, module, MOD_DESC)\n  File \"/tmp/ansible_cohesity_restore_vm_payload_61RW3z/__main__.py\", line 627, in <module>\n  File \"/tmp/ansible_cohesity_restore_vm_payload_61RW3z/__main__.py\", line 478, in main\nTypeError: unsupported operand
 type(s) for +: 'NoneType' and 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

The module should select the most recent snaphot from any existing protection job, if the job_name parameter is not given.

**Comment by naveena-maplelabs** [comment]
Available in the latest releases.
