### ISSUE TITLE
Capacity, snapshots and Restore

### ISSUE THREAD

**Issue by ecstaticninja** [cohesity/cohesity-ansible-role#43]
## ❓ Questions and Requests

Hey Folks,

A couple of questions

1) **Module: cohesity_facts:** Storage Domain Capacity

- The cohesity_facts module doesn't seem to return the Storage Domain's "_usagePerfStats_", "_localUsagePerfStats_", "_logicalStats_" and  "_dataUsageStats_". This is available via the API "/public/viewBoxes/{id}". 
- Is this something you can add to the module or does it already return these values and I'm not seeing it? 
- What would be good is to get the Storage Domain's physical/ logical capacity for the cluster.

2) **Module: cohesity_job:** Delete Backup Snapshot for View

- I couldn't find an option to delete a snapshot for a View. I am able to delete the entire protection job but not any individual snapshots within the protection job.

3) **Module:cohesity_restore_file:** Restore files for Views.

- Is there functionality to do this with the current module. Under environment I don't see an option for _Views_

Appreciate you help.
Thanks
ec

If it's an urgent request, Please contact us instead.
- [Email](cohesity-api-sdks@cohesity.com)

**Comment by naveena-maplelabs** [comment]
We are looking into this and add an enhancement to the cohesity [collections](https://galaxy.ansible.com/cohesity/dataprotect).
