### ISSUE TITLE
Solaris support

### ISSUE THREAD

**Issue by jerryhwg** [cohesity/cohesity-ansible-role#46]
## 🚀 Feature Request

I see currently RHEL/Ubuntu/Windows is supported.

Do you plan to support Solaris 11?

## Example or reference 

https://github.com/cohesity/cohesity-ansible-role/blob/master/docs/README.md

**Comment by naveena-maplelabs** [comment]
We are looking into this and add solaris support to the cohesity [collections](https://galaxy.ansible.com/cohesity/dataprotect).

**Comment by naveena-maplelabs** [comment]
https://jira.cohesity.com/browse/ENG-177477
