### ISSUE TITLE
Errors unless "excludeFilePaths" is Defined

### ISSUE THREAD

**Issue by dude0404** [cohesity/cohesity-ansible-role#52]
## 🐛 Bug Report

The "excludeFilePaths" variable in the Ansible role is not behaving as expected. The problems are:

1. When a Cohesity protection job is defined via Ansible WITHOUT "excludeFilePaths" set the protection job is succesfully created. Immediate & subsequent runs of the exact _same_ playbook fail with error until "excludeFilePaths" is defined.

2. When a Cohesity protection job is defined via Ansible WITH "excludeFilePaths" set the protection job is succesfully created. If you undefine "excludeFilePaths" later the playbook fails with error unless at least ONE "excludeFilePaths" is defined per included path.

## To Reproduce

1. Define a playbook to create a protection job for a single client. Do not define any "excludeFilePaths". 
2. Run the exact same playbook a second time.

Here is the playbook i am using:
`#=> Create a file based protection job for all linux sources
---
  - hosts: 127.0.0.1
    gather_facts: no
    roles:
      - cohesity-ansible-role-2.1.2
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          #cohesity_server: 10.22.149.28
          #cohesity_admin: "{{ username }}"
          #cohesity_password: "{{ password }}"
          #cohesity_validate_certs: False
          cohesity_protection:
              state: present
              job_name: "protect_vm"
              storage_domain: "DefaultStorageDomain"
              sources:
                - endpoint: esaabvm1
                  paths:
                    - includeFilePath: "/path1/"
                      excludeFilePaths:
                        - "/path1/exclude_path1" # This path should be present under /path1
                        - "/path1/exclude_path2" # This path should be present under /path1
                      skipNestedVolumes: False
                    - includeFilePath: "/path2"
                      excludeFilePaths:
                        - "/path2/exclude_path1" # This path should be present under /path2
                      skipNestedVolumes: False
              environment: "PhysicalFiles"
        #with_items: "{{ groups['linux'] }}"
`

## Expected behavior

Subsequent runs of the playbook should not error. They do unless "excludeFilePaths" is defined.

## Actual Behavior

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'excludeFilePaths'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n File \"/home/user/.ansible/tmp/ansible-tmp-1610495163.82-10786-279261066461986/AnsiballZ_cohesity_job.py\", line 102, in <module>\n _ansiballz_main()\n File \"/home/user/.ansible/tmp/ansible-tmp-1610495163.82-10786-279261066461986/AnsiballZ_cohesity_job.py\", line 94, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/home/user/.ansible/tmp/ansible-tmp-1610495163.82-10786-279261066461986/AnsiballZ_cohesity_job.py\", line 40, in invoke_module\n runpy.run_module(mod_name='ansible.modules.cohesity_job', init_globals=None, run_name='__main__', alter_sys=True)\n File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n fname, loader, pkg_name)\n File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n mod_name, mod_fname, mod_loader, pkg_name)\n File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n exec code in run_globals\n File \"/tmp/ansible_cohesity_job_payload_pnR1_H/ansible_cohesity_job_payload.zip/ansible/modules/cohesity_job.py\", line 1150, in <module>\n File \"/tmp/ansible_cohesity_job_payload_pnR1_H/ansible_cohesity_job_payload.zip/ansible/modules/cohesity_job.py\", line 951, in main\n File \"/tmp/ansible_cohesity_job_payload_pnR1_H/ansible_cohesity_job_payload.zip/ansible/modules/cohesity_job.py\", line 820, in update_job_util\nKeyError: 'excludeFilePaths'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by naveena-maplelabs** [comment]
@dude0404 Please upgrade to latest cohesity role, issue is resolved.
