### ISSUE TITLE
Nutanix acropolis support

### ISSUE THREAD

**Issue by merloon** [cohesity/cohesity-ansible-role#67]
Hello, 

Do you know when Nutanix acropolis will be supported in this module ? 
my infrascructure will move on full nutanix and this module can but really good for me. 

Regards, 

Fabien.

**Comment by pyashish** [comment]
Hi @merloon  we are looking into this request. Will have an update soon.

**Comment by naveena-maplelabs** [comment]
We are looking into this and add an enhancement to the cohesity [collections](https://galaxy.ansible.com/cohesity/dataprotect).

**Comment by naveena-maplelabs** [comment]
https://jira.cohesity.com/browse/ENG-285145
