### ISSUE TITLE
Include Archive Log Keep Days for the Oracle Protection sources

### ISSUE THREAD

**Issue by jxj191** [cohesity/cohesity-ansible-role#74]
## 🚀 Feature Request

Please include a feature where we can configure if the archive logs needs to be deleted from the Oracle Source and if yes, configure how many day to keep the archive logs at the Oracle server.
![Capture](https://user-images.githubusercontent.com/40396878/157471417-e7fae85b-85d5-427d-ab24-530c1dc4a2a4.JPG)

## Example or reference 

(Write your answer here)

**Comment by naveena-maplelabs** [comment]
We are looking into this and add support for the same in the cohesity [collections](https://galaxy.ansible.com/cohesity/dataprotect).

**Comment by naveena-maplelabs** [comment]
https://jira.cohesity.com/browse/ENG-263269
