### ISSUE TITLE
Creation Protection Policy with archival

### ISSUE THREAD

**Issue by bofrot** [cohesity/cohesity-ansible-role#77]
I get a error when i want to create a Protection Policy with archival.

Here we go this error :
fatal: [localhost]: FAILED! => {"changed": false, "error_class": "TypeError", "error_details": "must be str, not NoneType", "msg": "Unexpected error caused while managing the Cohesity Module."}

Here we go my create_policy.yml :
# Playbook to create protection policy.
---
- hosts: localhost
  gather_facts: true
  become: false
  collections:
    - cohesity.dataprotect
  tasks:
    - name: Create protection policy to cohesity server.
      cohesity_policy:
        cluster: "cohesity.xxxxxxxxxxx" #"{{ cohesity_server }}"
        username: "xxxxxxxxxxxxxxxxx" #"{{ cohesity_username }}"
        password: "xxxxxxxxxxxxxxxxx" #"{{ cohesity_password }}"
        validate_certs: false
        name: 'Ansible'
        state: 'present'
        incremental_backup_schedule:
          periodicity: Daily
        archival_copy: [
          target_name: "archive",
          target_type: 'Nas',
          days_to_retain: 1,
          periodicity: 'Month',
          copy_partial: true,
          multiplier: 1
        ]

Anyone can help me to find the trouble ?

**Comment by naveena-maplelabs** [comment]
@bofrot, You can refer the following playbook for policy creation.

---
- hosts: localhost
  gather_facts: true
  become: false
  collections:
    - cohesity.dataprotect
  tasks:
    - name: Create protection policy to cohesity server.
      cohesity_policy:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        name: 'Ansible'
        state: 'present'
        incremental_backup_schedule:
          periodicity: Daily
          archival_copy:
            _**day: Monday**_
            target_name: "target"
            target_type: 'Nas'
            days_to_retain: 1
            periodicity: **_Monthly_**
            multiplier: 1
