### ISSUE TITLE
Refresh source for Newly Created VM

### ISSUE THREAD

**Issue by takanoshota** [cohesity/cohesity-ansible-role#78]
## Can I add  "refresh source function" to cohesity_source or cohesity_job module

Hello, 

I'd like to automate creating VM and then creating a protection job for the new VM.
However, newly registered VM to vCenter doesn't  be seen unless source is refreshed manually.
So can I add a function to cohesity_source or cohesity_job module?

Which one is the best?

## Example or reference 

``
def refresh_source(module, self):
``

**Comment by naveena-maplelabs** [comment]
@takanoshota We have moved from ansible role to [ansible collections](https://github.com/cohesity/ansible-collection). We will add support for source refresh in our next collection release.

**Comment by takanoshota** [comment]
Thank you so much.

When are you going to release next version?

**Comment by naveena-maplelabs** [comment]
Refresh source feature is not supported, please check our latest playbooks for references
https://github.com/cohesity/ansible-collection/tree/main/playbooks/vmware-workflow
https://galaxy.ansible.com/cohesity/dataprotect
